### ISSUE TITLE
Breaks seem hardcoded

### ISSUE THREAD

**Issue by jaredhasenklein** [Nexus-for-FRC/Nexus#15]
Two related issues on lack of flexibility with breaks:

1) if breaks are completely removed, the blue banner still asks to confirm that breaks have ended 

2) there is no option (as far as I can tell) to modify break lengths without completely removing them and manually creating new breaks.

**Comment by eforbes** [comment]
Unfortunately this one is also complex due to the wide variety of ways offseasons modify the playoff structure.

If necessary, removing breaks in playoffs so they won't be displayed to teams is fine- but, as you noticed, the queuing sequence is dependent on the default breaks due to the way bracket progression is implemented and the requirement to have both alliances set before a match can be queued. Just skipping past the break prompts / manually overriding match statuses to be what you want is fine. I might be able to improve this for the 2024 offseason.

Taking a step back though my recommendation to offseasons is to not modify the playoff schedule at all. I think the consistency is better for the team experience.

**Comment by jaredhasenklein** [comment]
On your broader point, for offseasons that don't have any judges awards, the 15 minute breaks may be too long. The decision at CATT was to keep the schedule but make the 15 min breaks into 8 min breaks. Not that big of a deal, but a nice to have feature for events that don't have all the components of an official event.

**Comment by eforbes** [comment]
I think the general offseason rule of "if all teams are ready to go, go" works, and breaks can always be removed (to not display them to teams at all) or just queued past (queuer can declare the "break has ended" at any time).

I think adding specific break timing inputs will add too much unnecessary complexity but will keep this in mind if I revise the playoff queuing system in the future
